### ISSUE TITLE
Status of this?

### ISSUE THREAD

**Issue by gaurav21r** [PuppetJs/JSON-Patch-OT#2]
The visualisation looks great! Any updates on this project? Haven't seen much activity for a long time! Any help required?

**Comment by tomalec** [comment]
Thanks!
Yes, it's still supportedb
There is not much activity as so far everything works like charm ;)

I made a talk on this recently ar Zagreb Web Camp, you can take a look in here http://youtu.be/bTG7pIyzr7A

I thnink the thing that we need now most is good loking project page. Refreshed visualization, test cases in nodejs and few more operations left.

**Comment by gaurav21r** [comment]
@tomalec This is a very very promising library! And I think community participation can definitely increase. Maybe some marketing info on top of that good looking project page? 

Eg: If you are running this in production, maybe you can give an idea of the type of loads it handles. Like simultaneously *OTing* 100s of clients per minute or something?

Also, I think ShareJS is the KingPin :crown: of OT in Node.JS. Even there they have performance concerns as described here https://github.com/ottypes/json0#commentary Maybe you can give an idea of the time complexity of your algorithm?

**Comment by tomalec** [comment]
> some marketing info on top of that good looking project page
Definitely ;) but I have no idea on such things :|

Hm.. we should start measuring it, to give any numbers. By now I can say that we are applying few (up to 3) OTs per keystroke, and it works fine.

Good thing to mention is that performance of entire flow is not affected by the size of your JSON, but only by number of pending patches to transform against.

It would be great to be recognized in Node comunity as I think our great advantage on ShareJS is that we use standarized JSON Patch, not our custom magic thing.

I still have "writing clean white paper on OT flow and algebra" on my TODO list, but the bad thing is that this list is way to long.

**Comment by gaurav21r** [comment]
> some marketing info on top of that good looking project page
> Definitely ;) but I have no idea on such things :|
We can certainly help you out there!

My company is looking to invest in an OT Project. If I get the go ahead, I think we can collaborate on many fronts including marketing / design?

You should definitely write up a paper man! Especially since you've mastered in Mathematics! (I always thought Mathematics folk would be a bit more *academic* :wink: )

Also I was wondering is there any mathematical proof that the system will never be in conflict? Have you had a look at http://www.codecommit.com/blog/java/understanding-and-applying-operational-transformation ? I think its the most popular public facing tutorial on OT!

**Comment by tomalec** [comment]
> We can certainly help you out there!..

Cool :) I'll chat with my folks from PuppetJS team, and get back to you.

Thanks for googling me :wink:, but you know there are so many awesome things to do in the web, and the day is way to short ;) I know, I'm postponing it for too long.

>  I was wondering is there any mathematical proof that the system will never be in conflict

I would say that we can proof that the system will be in conflict :sunglasses:, we are here to resolve it. We could probably prove, that we could always transform, and that we will get some consistent result.
However, the way this result will look like is in question. Will some peer have more right to force result (ET/IT), or are the peers totally equal; will we rank/favor more recent version higher that old one, or in the opposite? - all those questions are rather in scope of individual preference than math.

> Have you had a look at..

Yep, that's good one :)

**Comment by gaurav21r** [comment]
Thanks @tomalec for all your prompt and detailed answers :smile: It reaffirms my faith that this project has the potential to go super popular in the node community. :star2: 

I'd really like to talk about some deep collaboration and some product specific questions. Mind sharing your email or some other Contact info where I can Direct Message you? If you would not like to reveal your email here, maybe you can shoot me an email at gaurav@rcorp.co.in so I can reply with the above?

**Comment by tomalec** [comment]
I'm really happy to hear that.

I have speak to my team, and if everything will go according to the plan, in 2-3 months, I should have some time to focus more on project page, visualizations, publicity etc. (by that time, I will be busy with [Juicy custom elements](http://github.com/Juicy), maybe you will find them useful as well ;) )

But in the meantime feel free to post issues, PRs, questions or comments here, StackOverflow or twitter (@tomalecpl), I'll try to help as much as I can.

**Comment by gaurav21r** [comment]
:+1:
